#!/bin/bash
if [ "$EUID" -ne 0 ]; then
  echo "This script must be run as root."
  exit
fi

case $1 in
  on )
    echo "Trying to enable discrete graphics"
    echo 1 > /sys/thinkpad_gsw/gpu_state
    modprobe nouveau modeset=2
    ;;
  off )
    echo "Trying to disable discrete graphics"
    modprobe -r nouveau
    echo 0 > /sys/thinkpad_gsw/gpu_state
    ;;
  *)
    echo "First parameter must be off or on"
    exit 1
    ;;
esac
