#!/bin/bash
if [ "$EUID" -ne 0 ]; then
  echo "(NOUVEAU) This script must be run as root."
  exit
fi

case $1 in
  on )
    echo "(NOUVEAU) Trying to enable discrete graphics"
    echo 1 > /sys/thinkpad_gsw/gpu_state && \
    sleep 2 && \
    modprobe nouveau
    ;;
  off )
    echo "(NOUVEAU) Trying to disable discrete graphics"
    modprobe -r nouveau && \
    echo 0 > /sys/thinkpad_gsw/gpu_state
    ;;
  *)
    echo "(NOUVEAU) First parameter must be off or on"
    exit 1
    ;;
esac
